const { DataTypes } = require("sequelize")
const sequelize = require("./initDB")

/**
 * Conversation model for storing AI pipeline results
 * Stores user prompts, summaries, optimized prompts, and code results
 */
const Conversation = sequelize.define(
  "Conversation",
  {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    userId: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "User identifier (optional)",
    },
    prompt: {
      type: DataTypes.TEXT,
      allowNull: false,
      comment: "Original user prompt",
    },
    summary: {
      type: DataTypes.TEXT,
      allowNull: true,
      comment: "Summary generated by phi3 model",
    },
    optimizedPrompt: {
      type: DataTypes.TEXT,
      allowNull: true,
      comment: "Optimized prompt generated by mistral model",
    },
    codeResult: {
      type: DataTypes.TEXT,
      allowNull: true,
      comment: "Code generated by deepseek-coder model",
    },
    timestamp: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
      comment: "Record creation timestamp",
    },
  },
  {
    tableName: "conversations",
    timestamps: true,
    createdAt: "timestamp",
    updatedAt: false,
  },
)

module.exports = Conversation
